CREATE TABLE "Materials" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Author" text NOT NULL,
    "Description" text,
    "Link" text,
    CONSTRAINT "PK_Materials" PRIMARY KEY ("Id")
);


CREATE TABLE "Tasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Question" text NOT NULL,
    "Option1" text NOT NULL,
    "Option2" text NOT NULL,
    "Option3" text NOT NULL,
    "Option4" text NOT NULL,
    "CorrectOption" integer NOT NULL,
    "Difficulty" integer NOT NULL,
    CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id")
);


CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "RegisteredAt" timestamp with time zone NOT NULL,
    "Role" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);


CREATE TABLE "UserTaskProgresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "TaskId" integer NOT NULL,
    "IsCompleted" boolean NOT NULL,
    CONSTRAINT "PK_UserTaskProgresses" PRIMARY KEY ("Id")
);


INSERT INTO "Tasks" ("Id", "CorrectOption", "Difficulty", "Option1", "Option2", "Option3", "Option4", "Question")
VALUES (1, 3, 1, 'Берлин', 'Мадрид', 'Париж', 'Рим', 'Столица Франции?');
INSERT INTO "Tasks" ("Id", "CorrectOption", "Difficulty", "Option1", "Option2", "Option3", "Option4", "Question")
VALUES (2, 2, 1, '3', '4', '5', '22', '2 + 2 = ?');
INSERT INTO "Tasks" ("Id", "CorrectOption", "Difficulty", "Option1", "Option2", "Option3", "Option4", "Question")
VALUES (3, 2, 2, 'Золото', 'Кислород', 'Олово', 'Серебро', 'Какой элемент обозначается символом ''O''?');


SELECT setval(
    pg_get_serial_sequence('"Tasks"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Tasks") + 1,
        nextval(pg_get_serial_sequence('"Tasks"', 'Id'))),
    false);


